### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Parsmadar** [DjangoEx/awesome-python-resources#147]
### I Want to Request the Following Reference(s) To Be Archived Publically
> Add as many references as you want to be archived in the repository in the following pattern.
- [ref1](#)
- [ref2](#)

> License approvement aggregation.
- [ ] All my mentioned references approve the [qualification parameters](https://github.com/DjangoEx/python-engineer-roadmap/blob/main/CONTRIBUTING.md#qualified-references).

**Comment by bobycloud** [comment]
Hi, What do you mean by creating this issue? It's not clear @Parsmadar

**Comment by lnxpy** [comment]
I'm closing it as there is no value in keeping it open. :)
